In [2]:
import pandas as pd
import numpy as np


from sklearn.preprocessing import OneHotEncoder

df=pd.read_csv("C:/Users/shrey/Desktop/sample1.csv")
df.drop(columns=['Unnamed: 0'],inplace=True)

In [3]:
df1=pd.DataFrame()

In [4]:
for i in df.columns:
    df1[i] = df[i].astype('category').cat.codes

In [5]:
df1.columns

Index(['Agent_id', 'status', 'lost_reason', 'budget', 'lease', 'movein',
       'source', 'source_city', 'source_country', 'utm_source', 'utm_medium',
       'des_city', 'des_country', 'room_type', 'lead_id'],
      dtype='object')

In [6]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression()


In [7]:
y=df1.status

In [8]:
x=df1.drop(columns=['status','Agent_id','lease'])

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.3,
    random_state=0)

x_train.shape, x_test.shape

((32421, 12), (13896, 12))

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
x_train

array([[ 0.03597131,  0.80071292, -0.53590714, ...,  0.12125692,
         2.41818356, -0.52753283],
       [ 0.55406371,  0.80071292,  2.15919731, ...,  0.12125692,
         0.48367251, -0.14542909],
       [-0.48212108, -1.85973122, -0.39045706, ...,  0.12125692,
        -0.48358301, -0.3219592 ],
       ...,
       [ 0.55406371, -0.24994747, -1.63961658, ...,  0.12125692,
        -0.48358301,  0.79111082],
       [-0.48212108, -0.77527766, -0.39045706, ...,  0.12125692,
        -0.48358301,  0.39698125],
       [ 1.93564343,  0.68858103, -1.3572723 , ...,  0.12125692,
        -0.48358301,  0.38121153]])

In [12]:
logisticRegr.fit(x_train, y_train)

LogisticRegression()

In [13]:
logisticRegr.predict(x_test[0].reshape(1,-1))

array([0], dtype=int8)

In [14]:
predictions = logisticRegr.predict(x_test)

In [15]:
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

In [16]:
logisticRegr.score(x_test, y_test)

0.9322107081174439

In [17]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=100, oob_score=True)
classifier_rf.fit(x_train, y_train)

# checking the oob score
classifier_rf.predict(x_test)
classifier_rf.oob_score_

0.9345177508405046

In [18]:

from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(x_train, y_train)  

y_pred= classifier.predict(x_test)  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [72]:
conda install -c conda-forge xgboost

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\shrey\anaconda3

  added / updated specs:
    - xgboost


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _py-xgboost-mutex-2.0      |            cpu_0          11 KB  conda-forge
    conda-4.14.0               |   py39hcbf5309_0         1.0 MB  conda-forge
    libxgboost-1.7.3           |       hd77b12b_0         1.5 MB
    py-xgboost-1.7.3           |   py39haa95532_0         197 KB
    python_abi-3.9             |           2_cp39           4 KB  conda-forge
    xgboost-1.7.3              |   py39haa95532_0          12 KB
    ------------------------------------------------------------
                                           Total:         2.8 MB

The following NEW packages will be INSTALLED:

  _py-xgboost-mutex  conda-forge/win-64::_py-xgboost-mutex-2.0-cpu_0
  libxgboost         pkgs/ma



==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda




In [71]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [73]:
from xgboost import XGBRegressor